# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaskWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TaskWindow(object):
    def setupUi(self, TaskWindow):
        TaskWindow.setObjectName("TaskWindow")
        TaskWindow.resize(320, 240)
        TaskWindow.setMaximumSize(QtCore.QSize(320, 240))
        TaskWindow.setWindowTitle("TASKS")
        self.mainWidget = QtWidgets.QWidget(TaskWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setMaximumSize(QtCore.QSize(320, 240))
        self.mainWidget.setObjectName("mainWidget")
        self.leftColumn = QtWidgets.QWidget(self.mainWidget)
        self.leftColumn.setGeometry(QtCore.QRect(0, 0, 320, 240))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftColumn.sizePolicy().hasHeightForWidth())
        self.leftColumn.setSizePolicy(sizePolicy)
        self.leftColumn.setMinimumSize(QtCore.QSize(320, 240))
        self.leftColumn.setObjectName("leftColumn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.leftColumn)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.keyWidgetCase = QtWidgets.QWidget(self.leftColumn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyWidgetCase.sizePolicy().hasHeightForWidth())
        self.keyWidgetCase.setSizePolicy(sizePolicy)
        self.keyWidgetCase.setMinimumSize(QtCore.QSize(35, 240))
        self.keyWidgetCase.setObjectName("keyWidgetCase")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.keyWidgetCase)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.key01_indicator = QtWidgets.QWidget(self.keyWidgetCase)
        self.key01_indicator.setMinimumSize(QtCore.QSize(20, 20))
        self.key01_indicator.setMaximumSize(QtCore.QSize(25, 25))
        self.key01_indicator.setAutoFillBackground(True)
        self.key01_indicator.setObjectName("key01_indicator")
        self.verticalLayout.addWidget(self.key01_indicator)
        self.key02_indicator = QtWidgets.QWidget(self.keyWidgetCase)
        self.key02_indicator.setMinimumSize(QtCore.QSize(20, 20))
        self.key02_indicator.setMaximumSize(QtCore.QSize(25, 25))
        self.key02_indicator.setAutoFillBackground(True)
        self.key02_indicator.setObjectName("key02_indicator")
        self.verticalLayout.addWidget(self.key02_indicator)
        self.key03_indicator = QtWidgets.QWidget(self.keyWidgetCase)
        self.key03_indicator.setMinimumSize(QtCore.QSize(20, 20))
        self.key03_indicator.setMaximumSize(QtCore.QSize(25, 25))
        self.key03_indicator.setAutoFillBackground(True)
        self.key03_indicator.setObjectName("key03_indicator")
        self.verticalLayout.addWidget(self.key03_indicator)
        self.horizontalLayout.addWidget(self.keyWidgetCase)
        self.rightColumn = QtWidgets.QWidget(self.leftColumn)
        self.rightColumn.setObjectName("rightColumn")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rightColumn)
        self.verticalLayout_2.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timeLabel = QtWidgets.QLabel(self.rightColumn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        self.timeLabel.setMinimumSize(QtCore.QSize(0, 95))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("color: darkblue;")
        self.timeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout_2.addWidget(self.timeLabel)
        self.haedLabel = QtWidgets.QLabel(self.rightColumn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.haedLabel.sizePolicy().hasHeightForWidth())
        self.haedLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.haedLabel.setFont(font)
        self.haedLabel.setStyleSheet("color: blue;")
        self.haedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.haedLabel.setObjectName("haedLabel")
        self.verticalLayout_2.addWidget(self.haedLabel)
        self.infoLabel = QtWidgets.QLabel(self.rightColumn)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infoLabel.setFont(font)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout_2.addWidget(self.infoLabel)
        self.horizontalLayout.addWidget(self.rightColumn)
        TaskWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(TaskWindow)
        QtCore.QMetaObject.connectSlotsByName(TaskWindow)

    def retranslateUi(self, TaskWindow):
        _translate = QtCore.QCoreApplication.translate
        self.timeLabel.setText(_translate("TaskWindow", "00:00"))
        self.haedLabel.setText(_translate("TaskWindow", "HEADLINE"))
        self.infoLabel.setText(_translate("TaskWindow", "TextLabel"))

